name: CI Pipeline

on:
    push:
      branch:
       - main

jobs:
    test-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: action/checkout@v4

        - name: Setup Node.js
          uses: actions/setup-node@v4

        - name: Install Dependencies
          run: npm Install

        - name: Run Tests
          run: npm test  